---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: master
      port: {{ .Values.service.master.port }}
      targetPort: {{ .Values.service.master.targetPort }}
    - name: slave
      port: {{ .Values.service.slave.port }}
      targetPort: {{ .Values.service.slave.targetPort }}
  selector:
    app: {{ .Values.name }}